export { default } from "next-auth/middleware";
import { withAuth } from "next-auth/middleware";

export const config = {
  matcher: [
    "/dashboard",
    "/profile-details",
    "/notification",
    "/chat-export",
    "/appearance",
    "/plans-billing",
    "/sessions",
    "/application",
    "/release-notes",
    "/help",
    "/text-generator",
    "/code-generator",
    "/email-generator",
    "/blog-post-generate",
    "/text-generator",
    "/code-generator",
    "/email-generator",
    "/profile-details",
    "/notification",
    "/chat-export",
    "/appearance",
    "/plans-billing",
    "/sessions",
    "/application",
    "/text-generator",
    "/code-generator",
    "/email-generator",
    "/blog-post-generate",
    "/text-generator",
    "/code-generator",
    "/email-generator",
    "/blog-post-generate",
  ],
};
